CREATE TABLE Authors (
    author_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    birthdate DATE
);

CREATE TABLE Books (
    book_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150),
    author_id INT,
    price DECIMAL(10, 2),
    publication_date DATE,
    FOREIGN KEY (author_id) REFERENCES Authors(author_id)
);

CREATE TABLE Orders (
    order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id INT,
    quantity INT,
    order_date DATE,
    FOREIGN KEY (book_id) REFERENCES Books(book_id)
);